micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
  application:
    name: otpservice
  server:
    cors:
      enabled: true
twilio:
  account:
  token:
  sid:
